image: chrome_nvm

matrix:
  - env: NODE_VERSION=10

cache:
  - node_modules

before_install:
  - nvm install $NODE_VERSION
  - npm config set spin false
  - npm config set progress false

install:
  - npm install

before_script:
  - npm run build
script:
  - npm test
after_script:
  - npm run build
