image: chrome_nvm

matrix:
  - env: NODE_VERSION=10 PERFORMANCE=false

before_install:
  - nvm install $NODE_VERSION
  - npm config set spin false
  - npm config set progress false

install:
  - yarn

script:
  - npm test
after_script:
  - npm run build
